In [1]:
##read the train data corpus
import pandas as pd
import xgboost as xgb
data = pd.read_csv('/home/dinushi/Desktop/ML/TheCompleteCorpus/TrainingCorpus.csv')
data

Text  intent
0                 මට නව ගිණුමක් විවෘත කරන්න ඕන       1
1              මට අලුත් ගිණුමක් විවෘත කරන්න ඕන       1
2                 අලුත් ගිණුමක් විවෘත කරන්න ඕන       1
3                    නව ගිණුමක් විවෘත කරන්න ඕන       1
4                 එකව්න්ට් එකක් ඕපන් කරන්න ඕනි       1
5                             අලුත් ගිණුමක් ඕන       1
6                            අලුත් ගිණුමක් ඕනි       1
7                               නව ගිණුමක් ඕනි       1
8                             නව ගිණුමක් හදන්න       1
9                          අලුත් ගිණුමක් හදන්න       1
10                     ගිණුමක් විවෘත කරන්න ඕනි       1
11          අලුත් එකව්න්ට් එකක් ඕපන් කරන්න ඕනි       1
12                    එකව්න්ට් එකක් ඕපන් කරන්න       1
13                      ගිණුමක් විවෘත කරන්න ඕන       1
14            මට අලුත් එකව්න්ට් එකක් අරින්න ඕන       1
15                        එකව්න්ට් එකක් අරින්න       1
16               මට අලුත් එකව්න්ට් එකක් අරින්න       1
17                   අලුත් එකව්න්ට් එකක් හදන්න       1
18            එකව්න්ට් එකක් ඕපන් කරන්නේ කොහොමද       1
19                        අලුත් ගිණුමක් අරින්න       1
20                           නව ගිණුමක් අරින්න       1
21                              ගිණුමක් අරින්න       1
22                         ඉතිරීකිරීමේ ගිණුමක්       2
23         ඉතිරීකිරීමේ ගිණුමක් විවෘත කරන්න ඕනි       2
24                  මට ඕන ඉතිරිකිරීමේ ගිණුමක්        2
25                 මට ඕනි ඉතිරිකිරීමේ ගිණුමක්        2
26         සේවින්ග්ස් එකව්න්ට් එකක් ඕපන් කරන්න       2
27                  ඉතිරිකිරීමේ ගිණුමක් අරින්න       2
28                     මට ඉතිරීකිරීමේ ගිණුමක්        2
29   මට සේවින්ග්ස් එකව්න්ට් එකක් ඕපන් කරන්න ඕන       2
..                                         ...     ...
134                                  නතර කරන්න       9
135                                   නවත්තන්න       9
136                ගිණුම විවෘත කිරීම නතර කරන්න       9
137                 ගිණුම විවෘත කිරීම නවත්තන්න       9
138                  දැන් මේ වැඩේ නතර කරන්න ඕන       9
139                          වැඩේ නතර කරන්න ඕන       9
140                             මට නවත්තන්න ඕන       9
141                                නවත්තන්න ඕන       9
142                                        ඇති       9
143                              වැඩේ නවත්තනවා       9
144                      මට මේක නවතලා දාන්න ඕන       9
145                                නවතලා දාන්න       9
146                    කල් පිරීමේදී ලබා ගන්නවා      10
147              පොළිය කල් පිරීමේදී ලබා ගන්නවා      10
148                         කල් පිරුනම ගන්නවා       10
149                   කල් පිරීමේදී ලබාගන්න ඕන       10
150                               කල් පිරීමේදී      10
151                  පොළිය කල් පිරීමේදී ගන්නවා      10
152                      කල් පිරුනම ලබා ගන්නවා      10
153                                 කල් පිරුනම      10
154                        කල් පිරීමේදී ගන්නවා      10
155                    කල් පිරීමේදී ලබාගන්න ඕන      10
156                     කල් පිරුනම  ලබාගන්න ඕන      10
157                          මාසිකව ලබා ගන්නවා      11
158                    පොළිය මාසිකව ලබා ගන්නවා      11
159                          මාසිකව ලබාගන්න ඕන      11
160                              මාසිකව ගන්නවා      11
161                                     මාසිකව      11
162                    පොළිය මාසිකව ලබාගන්න ඕන      11
163                        මාසිකව පොළිය ගන්නවා      11

[164 rows x 2 columns]

In [2]:
#convert dataframe to matrix
conv_arr= data.values

import numpy as np
#split matrix into 2 columns each into 1d array

arr2 = np.delete(conv_arr,[0],axis=1) #get lables column only
label_array = arr2.ravel() #create an array of labels
labels=np.array(label_array, dtype=np.float) #conver int to float

labels #the labels of the training data

array([ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  2.,  2.,  2.,  2.,
        2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,  2.,
        3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,  3.,
        3.,  3.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,  4.,
        4.,  4.,  4.,  4.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,  5.,
        5.,  5.,  5.,  5.,  5.,  5.,  5.,  6.,  6.,  6.,  6.,  6.,  6.,
        6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  6.,  7.,  7.,
        7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,  7.,
        7.,  7.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,  8.,
        8.,  8.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,
        9.,  9.,  9., 10., 10., 10., 10., 10., 10., 10., 10., 10., 10.,
       10., 11., 11., 11., 11., 11., 11., 11.])

In [3]:
#create the bag of word matrix for train text corpus
corpus = list(data.Text) #the training text array

#the whole set of words in the corpus is collected
word_array = []
for sentence in corpus:
    #print (sentence.split())
    word_array.extend(sentence.split())
word_array = (set(word_array))
word_array= list(word_array)
#print(word_array)

In [4]:
#create representation of each train text sentence  
sentence_list = []
for sentence in corpus:
    bag = [0]*len(word_array)
    for word in (sentence.split()):
        if(word in word_array):
           bag[(word_array.index(word))] = 1
    sentence_list.append(bag)
    
#the vector representation of each train text sentence     
sentence_list

[[0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0

In [5]:
from numpy import array, matrix
from scipy.sparse import csr_matrix

#convert the vector array to a sparse matrix
X_train_counts = csr_matrix(sentence_list)
X_train_counts.shape

(164, 95)

In [6]:
#find Tf_idf value vector for the each sentence in training set
from sklearn.feature_extraction.text import TfidfTransformer

tfidf_transformer = TfidfTransformer()
X_train_tfidf = tfidf_transformer.fit_transform(X_train_counts)
X_train_tfidf.shape #print the size of the matrix with tf-idf value of each word in the sentence

(164, 95)

In [7]:
from sklearn.naive_bayes import MultinomialNB

#train the SVM model
#clf = SGDClassifier(loss='hinge', penalty='l2',alpha=1e-3, n_iter=5, random_state=42).fit(X_train_tfidf, labels)
#clf = SGDClassifier().fit(X_train_tfidf, labels)
xg_reg = xgb.XGBRegressor(objective ='reg:linear', colsample_bytree = 0.185, learning_rate = 0.1591, max_depth = 5, alpha = 0.01, n_estimators = 22)
clf =xg_reg.fit(X_train_tfidf, labels)
#clf = MultinomialNB().fit(X_train_tfidf, labels)

In [8]:
#load test data
data_test = pd.read_csv('/home/dinushi/Desktop/ML/testset.csv')
data_test
#convert dataframe to matrix
conv_arr2= data_test.values

#split matrix into 2 columns each into 1d array
arr3 = np.delete(conv_arr2,[0],axis=1) 
label_array_t = arr3.ravel()
labels_test=np.array(label_array_t, dtype=np.float)
labels_test #labels of test data

array([1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 0., 1., 0., 0., 0., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.,
       1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 1., 1., 1., 0., 0., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2.

In [9]:
corpus_test = list(data_test.Text)

#represent each test sentence as a vector
sentence_list2 = []
for sentence in corpus_test:
    bag = [0]*len(word_array)
    for word in (sentence.split()):
        if(word in word_array):
           bag[(word_array.index(word))] = 1
    sentence_list2.append(bag)
        
sentence_list2 #the vector representation of each test sentence

X_train_counts_test = csr_matrix(sentence_list2)

tfidf_transformer = TfidfTransformer()
X_train_tfidf_test = tfidf_transformer.fit_transform(X_train_counts_test)
X_train_tfidf_test.shape #print the size of the matrix with tf-idf value of each test sentence

(634, 95)

In [10]:
#predict the values for test data
predicted_svm = clf.predict(X_train_tfidf_test)
predicted_svm = predicted_svm.astype(int)

#compare with test labels
np.mean(predicted_svm == labels_test)

0.5694006309148265

In [11]:
predicted_svm

array([2, 2, 2, 5, 2, 2, 3, 6, 2, 2, 2, 2, 2, 2, 2, 3, 1, 5, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 1, 2, 3, 2, 3, 2, 2, 3, 2, 2, 3, 4, 5, 2,
       6, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 3, 1, 3, 3, 3, 3, 3, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 3, 3, 3, 2, 3, 3, 3, 3, 3,
       3, 3, 2, 4, 3, 3, 3, 3, 2, 3, 2, 3, 2, 3, 2, 2, 2, 5, 3, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       5, 2, 2, 2, 2, 2, 3, 2, 2, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 6,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 1, 3, 3,
       3, 3, 2, 2, 2, 1, 1, 3, 2, 2, 4, 4, 4, 4, 4,

In [12]:
submission = pd.DataFrame()
submission['intent'] = pd.Series(predicted_svm).round().astype(int)

submission.to_csv(r'/home/dinushi/Desktop/ML/output_intents.csv')